[package]
name = "kale_duration"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", optional = true }

[dev-dependencies]
serde_json = {version = "1"}